"""Pairwise sentence similarity utilities for two Tibetan texts."""

from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np

from .embeddings import DEFAULT_MODEL_ID, TextEmbedder
from .normalization import normalize_text
from .pipeline import resolve_segmenter


@dataclass(slots=True)
class PairMatch:
    """One ranked sentence-pair match."""

    rank: int
    score: float
    i: int
    j: int
    sentence_a: str
    sentence_b: str


@dataclass(slots=True)
class PairwiseArtifacts:
    """Artifact paths generated by a pairwise run."""

    topk_csv: Path
    topk_jsonl: Path
    manifest_json: Path
    similarity_npy: Path | None = None


@dataclass(slots=True)
class PairwiseResult:
    """In-memory result bundle for pairwise matching."""

    matches: list[PairMatch]
    segments_a: list[str]
    segments_b: list[str]
    similarity_matrix: np.ndarray


def segment_text_to_sentences(
    text: str,
    engine: str = "botok_ours",
    source_format: str = "unicode",
    botok_cache_dir: str | Path | None = None,
    min_syllables: int = 4,
) -> list[str]:
    """Normalize and segment one text into sentence strings."""
    normalized = normalize_text(text, source_format=source_format)
    segmenter = resolve_segmenter(
        engine=engine,
        dialect_pack_dir=botok_cache_dir,
        min_syllables=min_syllables,
    )
    segmented = segmenter.segment(normalized)
    return [segment.text for segment in segmented if segment.text.strip()]


def cosine_similarity_matrix(embeddings_a: np.ndarray, embeddings_b: np.ndarray) -> np.ndarray:
    """Compute cosine similarity matrix with shape [len(A), len(B)]."""
    if embeddings_a.ndim != 2 or embeddings_b.ndim != 2:
        raise ValueError("Embeddings must be rank-2 arrays.")
    if embeddings_a.shape[1] != embeddings_b.shape[1]:
        raise ValueError("Embedding dimensions must match.")
    if embeddings_a.shape[0] == 0 or embeddings_b.shape[0] == 0:
        return np.empty((embeddings_a.shape[0], embeddings_b.shape[0]), dtype=np.float32)

    a_norm = _row_normalize(embeddings_a)
    b_norm = _row_normalize(embeddings_b)
    return (a_norm @ b_norm.T).astype(np.float32)


def global_top_k_matches(
    matrix: np.ndarray,
    sentences_a: list[str],
    sentences_b: list[str],
    k: int,
) -> list[PairMatch]:
    """Return globally highest-scoring i,j sentence pairs."""
    if matrix.ndim != 2:
        raise ValueError("Similarity matrix must be rank-2.")
    if matrix.shape != (len(sentences_a), len(sentences_b)):
        raise ValueError("Matrix shape must match sentence list lengths.")
    if k <= 0 or matrix.size == 0:
        return []

    flat = matrix.ravel()
    k_eff = min(k, flat.size)
    if k_eff == flat.size:
        top_indices = np.argsort(flat)
    else:
        top_indices = np.argpartition(flat, -k_eff)[-k_eff:]

    # Stable deterministic order: score desc, then i asc, then j asc.
    ordered = sorted(
        top_indices.tolist(),
        key=lambda idx: (-float(flat[idx]), idx // matrix.shape[1], idx % matrix.shape[1]),
    )

    matches: list[PairMatch] = []
    for rank, flat_idx in enumerate(ordered, start=1):
        i = flat_idx // matrix.shape[1]
        j = flat_idx % matrix.shape[1]
        matches.append(
            PairMatch(
                rank=rank,
                score=float(matrix[i, j]),
                i=i,
                j=j,
                sentence_a=sentences_a[i],
                sentence_b=sentences_b[j],
            )
        )
    return matches


def run_pairwise_similarity(
    text_a: str,
    text_b: str,
    output_dir: str | Path,
    *,
    engine: str = "botok_ours",
    source_format: str = "unicode",
    botok_cache_dir: str | Path | None = ".cache/botok/dialect_packs",
    min_syllables: int = 4,
    model_id: str = DEFAULT_MODEL_ID,
    batch_size: int = 8,
    top_k: int = 100,
    save_similarity_npy: bool = False,
) -> PairwiseArtifacts:
    """Run segment -> embed -> similarity -> global top-k for two texts."""
    sentences_a = segment_text_to_sentences(
        text_a,
        engine=engine,
        source_format=source_format,
        botok_cache_dir=botok_cache_dir,
        min_syllables=min_syllables,
    )
    sentences_b = segment_text_to_sentences(
        text_b,
        engine=engine,
        source_format=source_format,
        botok_cache_dir=botok_cache_dir,
        min_syllables=min_syllables,
    )

    embedder = TextEmbedder(model_id=model_id, batch_size=batch_size, normalize_embeddings=True)
    embeddings_a = embedder.encode(sentences_a).embeddings
    embeddings_b = embedder.encode(sentences_b).embeddings
    matrix = cosine_similarity_matrix(embeddings_a, embeddings_b)
    matches = global_top_k_matches(matrix, sentences_a, sentences_b, top_k)

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    topk_csv = output_dir / "topk_pairs.csv"
    topk_jsonl = output_dir / "topk_pairs.jsonl"
    manifest_json = output_dir / "run_manifest.json"
    write_topk_csv(matches, topk_csv)
    write_topk_jsonl(matches, topk_jsonl)

    similarity_npy: Path | None = None
    if save_similarity_npy:
        similarity_npy = output_dir / "similarity_matrix.npy"
        np.save(similarity_npy, matrix)

    manifest = {
        "engine": engine,
        "source_format": source_format,
        "model_id": model_id,
        "batch_size": batch_size,
        "top_k_requested": top_k,
        "top_k_returned": len(matches),
        "segment_count_a": len(sentences_a),
        "segment_count_b": len(sentences_b),
        "matrix_shape": list(matrix.shape),
        "topk_csv": str(topk_csv),
        "topk_jsonl": str(topk_jsonl),
        "similarity_npy": str(similarity_npy) if similarity_npy else None,
    }
    manifest_json.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    return PairwiseArtifacts(
        topk_csv=topk_csv,
        topk_jsonl=topk_jsonl,
        manifest_json=manifest_json,
        similarity_npy=similarity_npy,
    )


def write_topk_csv(matches: list[PairMatch], output_path: str | Path) -> Path:
    """Write ranked matches to CSV."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["rank", "score", "i", "j", "sentence_a", "sentence_b"]
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for match in matches:
            writer.writerow(asdict(match))
    return output_path


def write_topk_jsonl(matches: list[PairMatch], output_path: str | Path) -> Path:
    """Write ranked matches to JSONL."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        for match in matches:
            handle.write(json.dumps(asdict(match), ensure_ascii=False))
            handle.write("\n")
    return output_path


def _row_normalize(embeddings: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    norms = np.clip(norms, a_min=1e-12, a_max=None)
    return embeddings / norms
